"""add currency column to transactions table

Revision ID: 20453cb8d0f3
Revises: b3acf4e13d7a
Create Date: 2025-11-11 18:31:29.620420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20453cb8d0f3'
down_revision: Union[str, Sequence[str], None] = 'b3acf4e13d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('currency', sa.String(length=3), server_default='KES', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'currency')
    # ### end Alembic commands ###
