"""alter completed_at column in transactions table

Revision ID: 4b2a9cdb226e
Revises: e681655f56bf
Create Date: 2025-11-10 18:23:51.647763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2a9cdb226e'
down_revision: Union[str, Sequence[str], None] = 'e681655f56bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'completed_at',
               existing_type=sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), 
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'completed_at',
               existing_type=sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), 
               existing_nullable=False)
    # ### end Alembic commands ###
