"""create public_id column in wallets table

Revision ID: 83bece1f8384
Revises: 20453cb8d0f3
Create Date: 2025-11-12 13:47:46.361063

"""
from typing import Sequence, Union
import shortuuid
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83bece1f8384'
down_revision: Union[str, Sequence[str], None] = '20453cb8d0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('public_id', sa.String(length=8), nullable=True))

    ### generate public id for existing rows###
    connection = op.get_bind()
    wallets = connection.execute(sa.text("SELECT id FROM wallets")).fetchall()

    for w in wallets:
        public_id = shortuuid.ShortUUID(alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ").random(length=8)
        connection.execute(sa.text("UPDATE wallets SET public_id = :pid WHERE id = :id"), {"pid":public_id, "id":w.id})
    
    ###alter column to be non-nullable###
    op.alter_column("wallets", "public_id", nullable=False)
    op.create_unique_constraint(None, 'wallets', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='unique')
    op.drop_column('wallets', 'public_id')
    # ### end Alembic commands ###
