"""alter references columns in transactions table

Revision ID: adddbccef85e
Revises: d13351aac197
Create Date: 2025-11-13 17:45:57.165349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adddbccef85e'
down_revision: Union[str, Sequence[str], None] = 'd13351aac197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
