"""alter id column in refresh_tokens table

Revision ID: b738fb905881
Revises: 81ccfa1bce94
Create Date: 2025-11-06 17:38:27.172449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b738fb905881'
down_revision: Union[str, Sequence[str], None] = '81ccfa1bce94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###s
    # ### end Alembic commands ###
