"""add column of balance in ledger entries table

Revision ID: c55978f3979a
Revises: adddbccef85e
Create Date: 2025-11-13 18:47:04.428088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55978f3979a'
down_revision: Union[str, Sequence[str], None] = 'adddbccef85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_entries', sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ledger_entries', 'balance_after')
    # ### end Alembic commands ###
