"""add index to account_number column of wallets table

Revision ID: d13351aac197
Revises: db8468efba1a
Create Date: 2025-11-13 17:29:31.631422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13351aac197'
down_revision: Union[str, Sequence[str], None] = 'db8468efba1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wallets_account_number'), 'wallets', ['account_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('wallets_account_number_key'), 'wallets', ['account_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
