"""alter is_active column of wallets table

Revision ID: db8468efba1a
Revises: 83bece1f8384
Create Date: 2025-11-12 15:08:33.239392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8468efba1a'
down_revision: Union[str, Sequence[str], None] = '83bece1f8384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'is_active',server_default=sa.text('True'), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'is_active',server_default=sa.text('True'), nullable=False)
    # ### end Alembic commands ###
