"""alter columns in transactions table

Revision ID: e681655f56bf
Revises: 11c17cd0ebb8
Create Date: 2025-11-10 17:17:01.764351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e681655f56bf'
down_revision: Union[str, Sequence[str], None] = '11c17cd0ebb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_wallet_account_number', sa.UUID(), nullable=False))
    op.add_column('transactions', sa.Column('receiver_wallet_account_number', sa.UUID(), nullable=False))
    op.alter_column('transactions', 'reference',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('transactions', 'sender_ref',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('transactions', 'receiver_ref',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_constraint(op.f('transactions_sender_wallet_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_receiver_wallet_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'wallets', ['receiver_wallet_account_number'], ['id'])
    op.create_foreign_key(None, 'transactions', 'wallets', ['sender_wallet_account_number'], ['id'])
    op.drop_column('transactions', 'receiver_wallet_id')
    op.drop_column('transactions', 'sender_wallet_id')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_wallet_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('receiver_wallet_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_receiver_wallet_id_fkey'), 'transactions', 'wallets', ['receiver_wallet_id'], ['id'])
    op.create_foreign_key(op.f('transactions_sender_wallet_id_fkey'), 'transactions', 'wallets', ['sender_wallet_id'], ['id'])
    op.alter_column('transactions', 'receiver_ref',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('transactions', 'sender_ref',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('transactions', 'reference',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('transactions', 'id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('transactions', 'receiver_wallet_account_number')
    op.drop_column('transactions', 'sender_wallet_account_number')
    # ### end Alembic commands ###
