"""add account_number to wallets table

Revision ID: f3b5397ad9c6
Revises: b738fb905881
Create Date: 2025-11-08 21:44:56.670121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b5397ad9c6'
down_revision: Union[str, Sequence[str], None] = 'b738fb905881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('account_number', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'wallets', ['account_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='unique')
    op.drop_column('wallets', 'account_number')
    # ### end Alembic commands ###
